version: 2.1
jobs:
  build:
    docker:
      - image: docker:20.10.2
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker Image
          command: |
            docker build -t hello-Senthil .
          environment:
            DOCKER_USER: sankarsenthil002
            DOCKER_PASS: dckr_pat_RtWLXQwc99nKTeoB0VPLxvjk510
      - run:
          name: Push Docker Image
          command: |
            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
            docker push your-docker-hub-username/your-docker-image
