apiVersion: v1
kind: Service
metadata:
  name: hello-world
  labels:
    app: hello-world
spec:
  ports:
    - port: 3300
  selector:
    app: hello-world
    tier: frontend
  type: LoadBalancer
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: hello-world
  labels:
    app: hello-world
spec:
  selector:
    matchLabels:
      app: hello-world
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: hello-world
        tier: frontend
    spec:
      containers:
      - image: gcr.io/refreshing-glow-372901/hello-world
        name: hello-world
        ports:
        - containerPort: 3300
          name: hello-world