apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-deployment
  labels:
    app: helloworld
spec:
  replicas: 3
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: hello-world
        image: us-central1-docker.pkg.dev/refreshing-glow-372901/quickstart-docker-repo/hello-world:tag1
        ports:
        - containerPort: 8800